"""
build_app_data.py
-----------------
Derives clean, app-ready datasets from the raw FIFA 4_17 revenue package.

Produces everything under data/app_ready/ and data/simulation/ that the
Streamlit app consumes. Run this once; the app loads pre-built CSVs.

Core design decisions:
  1. Venue-level revenue is NOT in the raw executed outputs. We build a
     transparent venue x stage scenario grid grounded in the recovered
     stage medians (per the executed project summary), plus a realistic
     FIFA 2026 venue + match-allocation table.
  2. All revenue is labeled "proxy / scenario revenue" per the assumption
     registry. This is never presented as audited observed revenue.
  3. The main model for feature importance is revenue_proxy_no_stage_feature.
     Because the raw file does not break that view out separately, we
     derive it by taking the xgboost revenue_proxy_full ranking and
     REMOVING the mechanical stage_detail row (see Spec Decision table).
  4. Draw simulation outputs are generated by a constrained Monte Carlo
     over the FIFA 2026 pot structure, clearly labeled as a demo sim.
"""

from __future__ import annotations

import itertools
import json
import random
from pathlib import Path

import numpy as np
import pandas as pd

HERE = Path(__file__).parent
RAW = HERE / "data" / "raw"
OUT_APP = HERE / "data" / "app_ready"
OUT_SIM = HERE / "data" / "simulation"
OUT_APP.mkdir(parents=True, exist_ok=True)
OUT_SIM.mkdir(parents=True, exist_ok=True)

RNG = np.random.default_rng(26)
random.seed(26)


# =============================================================================
# 1. FIFA 2026 venue + match-allocation master table
# =============================================================================
# Capacities reflect publicly announced FIFA 2026 host-venue capacities
# (rounded). Match allocations are illustrative and sum to 104.
VENUES = [
    # (venue, city, state, country, capacity, group_matches, ro32, ro16, qf, sf, third, final)
    ("MetLife Stadium",          "New York/New Jersey", "NJ", "USA",    82500, 5, 0, 1, 1, 0, 0, 1),
    ("AT&T Stadium",             "Dallas/Arlington",    "TX", "USA",    80000, 5, 0, 1, 1, 1, 0, 0),
    ("SoFi Stadium",             "Los Angeles",         "CA", "USA",    70000, 6, 0, 1, 1, 0, 0, 0),
    ("Mercedes-Benz Stadium",    "Atlanta",             "GA", "USA",    71000, 5, 0, 1, 1, 1, 0, 0),
    ("Arrowhead Stadium",        "Kansas City",         "MO", "USA",    76416, 4, 0, 1, 1, 0, 0, 0),
    ("Hard Rock Stadium",        "Miami Gardens",       "FL", "USA",    65000, 5, 0, 1, 0, 0, 1, 0),
    ("NRG Stadium",              "Houston",             "TX", "USA",    72220, 5, 0, 1, 1, 0, 0, 0),
    ("Levi's Stadium",           "Santa Clara",         "CA", "USA",    68500, 5, 0, 1, 0, 0, 0, 0),
    ("Lincoln Financial Field",  "Philadelphia",        "PA", "USA",    69000, 5, 0, 1, 0, 0, 0, 0),
    ("Gillette Stadium",         "Foxborough",          "MA", "USA",    65878, 5, 0, 1, 1, 0, 0, 0),
    ("Lumen Field",              "Seattle",             "WA", "USA",    68740, 5, 0, 1, 0, 0, 0, 0),
    ("BMO Field",                "Toronto",             "ON", "Canada", 45000, 6, 0, 1, 0, 0, 0, 0),
    ("BC Place",                 "Vancouver",           "BC", "Canada", 54500, 6, 0, 1, 0, 0, 0, 0),
    ("Estadio Azteca",           "Mexico City",         "CDMX", "Mexico", 87000, 4, 0, 1, 0, 0, 0, 0),
    ("Estadio Akron",            "Guadalajara",         "JAL", "Mexico", 48000, 3, 0, 1, 0, 0, 0, 0),
    ("Estadio BBVA",             "Monterrey",           "NL", "Mexico", 51000, 3, 0, 1, 0, 0, 0, 0),
]

venue_cols = ["venue", "city", "state", "country", "capacity",
              "group_matches", "ro32_matches", "ro16_matches",
              "qf_matches", "sf_matches", "third_matches", "final_matches"]
venues_df = pd.DataFrame(VENUES, columns=venue_cols)
venues_df["total_matches"] = venues_df.iloc[:, 5:].sum(axis=1)
assert venues_df["total_matches"].sum() == 104, (
    f"Expected 104 matches, got {venues_df['total_matches'].sum()}"
)


# =============================================================================
# 2. Stage economics (from the recovered executed project summary)
# =============================================================================
stage_summary_raw = pd.read_csv(RAW / "FIFA_Revenue_Stage_Summary_0417_fixed.csv")

# Map our allocation columns to the executed stage buckets
STAGE_MAP = [
    ("group_matches",  "Group",          622, 43025, 120,  4_700_000),
    ("ro32_matches",   "Early knockout",   9, 16120, 145,  2_000_000),
    ("ro16_matches",   "Round of 16",     63, 51593, 175,  8_100_000),
    ("qf_matches",     "Quarter-finals",  62, 44544, 250, 10_500_000),
    ("sf_matches",     "Semi-finals",     34, 58956, 350, 21_400_000),
    ("third_matches",  "Third place",     18, 52569, 210, 10_900_000),
    ("final_matches",  "Final",           19, 76470, 450, 33_100_000),
]
stage_cols = ["alloc_col", "stage", "matches_in_executed", "avg_attendance",
              "base_price_usd", "median_proxy_revenue_usd"]
stage_df = pd.DataFrame(STAGE_MAP, columns=stage_cols)


# Reference capacity used to scale per-match revenue against stage median.
# A 70k-seat venue hits the stage median exactly; larger venues earn more,
# smaller venues earn less, on a linear scale clipped at [0.45, 1.35].
REF_CAPACITY = 70000


def _cap_factor(capacity: float) -> float:
    return float(np.clip(capacity / REF_CAPACITY, 0.45, 1.35))


# =============================================================================
# 3. Venue x Stage revenue grid (LOW / BASE / HIGH scenarios)
# =============================================================================
rows = []
for _, v in venues_df.iterrows():
    for _, s in stage_df.iterrows():
        n = int(v[s["alloc_col"]])
        if n <= 0:
            continue
        cap_scale = _cap_factor(v["capacity"])
        per_match_base = s["median_proxy_revenue_usd"] * cap_scale
        rows.append({
            "venue": v["venue"],
            "city": v["city"],
            "state": v["state"],
            "country": v["country"],
            "capacity": v["capacity"],
            "stage": s["stage"],
            "n_matches": n,
            "per_match_base_usd": round(per_match_base),
            "per_match_low_usd": round(per_match_base * 0.80),
            "per_match_high_usd": round(per_match_base * 1.20),
            "total_base_usd": round(per_match_base * n),
            "total_low_usd": round(per_match_base * 0.80 * n),
            "total_high_usd": round(per_match_base * 1.20 * n),
        })
venue_stage_df = pd.DataFrame(rows)
venue_stage_df.to_csv(OUT_APP / "app_venue_stage_revenue.csv", index=False)


# =============================================================================
# 4. Venue summary (collapsed over all stages, base scenario)
# =============================================================================
venue_summary = (
    venue_stage_df.groupby(["venue", "city", "state", "country", "capacity"], as_index=False)
    .agg(total_matches=("n_matches", "sum"),
         total_revenue_base_usd=("total_base_usd", "sum"),
         total_revenue_low_usd=("total_low_usd", "sum"),
         total_revenue_high_usd=("total_high_usd", "sum"))
    .sort_values("total_revenue_base_usd", ascending=False)
    .reset_index(drop=True)
)
venue_summary["avg_revenue_per_match_usd"] = (
    venue_summary["total_revenue_base_usd"] / venue_summary["total_matches"]
).round(0)
# Flag host highlights
venue_summary["is_final_host"] = venue_summary["venue"].eq("MetLife Stadium")
venue_summary.to_csv(OUT_APP / "app_venue_summary.csv", index=False)


# =============================================================================
# 5. Country summary
# =============================================================================
country_summary = (
    venue_stage_df.groupby("country", as_index=False)
    .agg(venues=("venue", "nunique"),
         matches=("n_matches", "sum"),
         total_revenue_base_usd=("total_base_usd", "sum"),
         total_revenue_low_usd=("total_low_usd", "sum"),
         total_revenue_high_usd=("total_high_usd", "sum"))
    .sort_values("total_revenue_base_usd", ascending=False)
    .reset_index(drop=True)
)
country_summary["share_of_total"] = (
    country_summary["total_revenue_base_usd"]
    / country_summary["total_revenue_base_usd"].sum()
).round(4)
country_summary.to_csv(OUT_APP / "app_country_summary.csv", index=False)


# =============================================================================
# 6. Stage summary for the app (cleaner version of the raw stage file)
# =============================================================================
stage_clean = stage_df.rename(columns={
    "alloc_col": "allocation_column",
    "stage": "stage",
    "matches_in_executed": "matches_executed_project",
    "avg_attendance": "avg_attendance_executed",
    "base_price_usd": "assumed_ticket_price_usd",
    "median_proxy_revenue_usd": "median_proxy_revenue_usd",
})
tournament_matches = (
    venue_stage_df.groupby("stage", as_index=False)["n_matches"].sum()
    .rename(columns={"n_matches": "matches_2026_allocation"})
)
stage_clean = stage_clean.merge(tournament_matches, on="stage", how="left")
stage_clean["tournament_proxy_revenue_usd"] = (
    stage_clean["matches_2026_allocation"] * stage_clean["median_proxy_revenue_usd"]
)
stage_clean = stage_clean.drop(columns=["allocation_column"])
stage_clean.to_csv(OUT_APP / "app_stage_summary.csv", index=False)


# =============================================================================
# 7. Model comparison (scorecard)
# =============================================================================
metrics = pd.read_csv(RAW / "FIFA_Revenue_Model_Metrics_0417_fixed.csv")
metrics["rmse_display"] = metrics.apply(
    lambda r: f"{r['rmse']:,.0f} attendees" if r["rmse_unit"] == "attendees"
    else f"${r['rmse'] / 1e6:,.2f}M",
    axis=1,
)
metrics.to_csv(OUT_APP / "app_model_comparison.csv", index=False)


# =============================================================================
# 8. Feature importance - MAIN MODEL = revenue_proxy_no_stage_feature
#    Derived by removing the mechanical stage_detail row from the executed
#    xgboost revenue_proxy_full ranking, per the Spec Decision table.
#    Also keep the attendance-signal ranking as a cross-check.
# =============================================================================
fi_all = pd.read_csv(RAW / "FIFA_Revenue_Feature_Importance_All_0417_fixed.csv")

# Main: revenue_proxy view with stage_detail removed
main_model = fi_all[
    (fi_all["model_view"] == "revenue_proxy_full")
    & (fi_all["feature"] != "stage_detail")
].copy()
main_model = main_model[main_model["importance"] > 0]  # drop weak/null signals
main_model["model_view_display"] = "revenue_proxy_no_stage_feature (main model)"
main_model["share_of_total"] = (
    main_model["importance"] / main_model["importance"].sum()
).round(4)
main_model = main_model.sort_values("importance", ascending=False).reset_index(drop=True)
main_model["rank"] = main_model.index + 1
main_model.to_csv(OUT_APP / "app_feature_importance_main.csv", index=False)

# Secondary: attendance signal
att_model = fi_all[fi_all["model_view"] == "attendance_signal_model"].copy()
att_model["share_of_total"] = (
    att_model["importance"] / att_model["importance"].sum()
).round(4)
att_model = att_model.sort_values("importance", ascending=False).reset_index(drop=True)
att_model["rank"] = att_model.index + 1
att_model.to_csv(OUT_APP / "app_feature_importance_attendance.csv", index=False)

# Benchmark reference: revenue_proxy_full (includes stage_detail)
ref_model = fi_all[fi_all["model_view"] == "revenue_proxy_full"].copy()
ref_model["share_of_total"] = (
    ref_model["importance"] / ref_model["importance"].sum()
).round(4)
ref_model = ref_model.sort_values("importance", ascending=False).reset_index(drop=True)
ref_model.to_csv(OUT_APP / "app_feature_importance_benchmark.csv", index=False)


# =============================================================================
# 9. Assumptions registry
# =============================================================================
assumptions = pd.read_csv(RAW / "FIFA_Revenue_Assumptions_0417_fixed.csv")
assumptions.to_csv(OUT_APP / "app_assumptions.csv", index=False)


# =============================================================================
# 10. Draw simulation
#     Constrained Monte Carlo over a FIFA-2026-style 12-group draw with
#     4 pots of 12 teams each. Confederation cap: at most 1 UEFA team
#     per group (simplified from the real rule for demo purposes).
#     Host-slot constraints: USA in Group D, Mexico in Group A, Canada in Group B.
# =============================================================================

TEAMS = [
    # pot, team, confederation
    # Pot 1 (seeded)
    (1, "Argentina",    "CONMEBOL"),
    (1, "France",       "UEFA"),
    (1, "Spain",        "UEFA"),
    (1, "England",      "UEFA"),
    (1, "Brazil",       "CONMEBOL"),
    (1, "Portugal",     "UEFA"),
    (1, "Netherlands",  "UEFA"),
    (1, "Germany",      "UEFA"),
    (1, "Belgium",      "UEFA"),
    (1, "Mexico",       "CONCACAF"),   # host A
    (1, "USA",          "CONCACAF"),   # host D
    (1, "Canada",       "CONCACAF"),   # host B
    # Pot 2
    (2, "Italy",        "UEFA"),
    (2, "Morocco",      "CAF"),
    (2, "Croatia",      "UEFA"),
    (2, "Japan",        "AFC"),
    (2, "Uruguay",      "CONMEBOL"),
    (2, "Senegal",      "CAF"),
    (2, "Colombia",     "CONMEBOL"),
    (2, "Switzerland",  "UEFA"),
    (2, "Denmark",      "UEFA"),
    (2, "Ecuador",      "CONMEBOL"),
    (2, "South Korea",  "AFC"),
    (2, "Iran",         "AFC"),
    # Pot 3
    (3, "Australia",    "AFC"),
    (3, "Serbia",       "UEFA"),
    (3, "Poland",       "UEFA"),
    (3, "Egypt",        "CAF"),
    (3, "Algeria",      "CAF"),
    (3, "Tunisia",      "CAF"),
    (3, "Nigeria",      "CAF"),
    (3, "Norway",       "UEFA"),
    (3, "Sweden",       "UEFA"),
    (3, "Paraguay",     "CONMEBOL"),
    (3, "Turkey",       "UEFA"),
    (3, "Austria",      "UEFA"),
    # Pot 4
    (4, "Panama",       "CONCACAF"),
    (4, "Costa Rica",   "CONCACAF"),
    (4, "Jamaica",      "CONCACAF"),
    (4, "Qatar",        "AFC"),
    (4, "Saudi Arabia", "AFC"),
    (4, "Uzbekistan",   "AFC"),
    (4, "Iraq",         "AFC"),
    (4, "Ghana",        "CAF"),
    (4, "Cameroon",     "CAF"),
    (4, "Ivory Coast",  "CAF"),
    (4, "New Zealand",  "OFC"),
    (4, "Bolivia",      "CONMEBOL"),
]
teams_df = pd.DataFrame(TEAMS, columns=["pot", "team", "confederation"])
teams_df.to_csv(OUT_APP / "app_teams.csv", index=False)

GROUP_LETTERS = list("ABCDEFGHIJKL")

HOST_SLOTS = {"Mexico": "A", "Canada": "B", "USA": "D"}  # host-country group assignment


def _confederation_ok(groups, gi, conf):
    """Real FIFA 2026 rule (simplified): max 2 UEFA per group, max 1 from any
    other confederation per group."""
    confs_here = [c for _, c in groups[gi]]
    if conf == "UEFA":
        return confs_here.count("UEFA") < 2
    return conf not in confs_here


def _place_pot(groups, pot_teams, target_size):
    """Backtracking placement of a pot. Each group must reach target_size after
    this pot is placed."""
    teams = list(pot_teams)
    random.shuffle(teams)

    def recurse(ti):
        if ti == len(teams):
            return True
        team, conf = teams[ti]
        # Try each group that still needs a team from this pot
        candidates = [gi for gi in range(12) if len(groups[gi]) == target_size - 1]
        random.shuffle(candidates)
        for gi in candidates:
            if _confederation_ok(groups, gi, conf):
                groups[gi].append((team, conf))
                if recurse(ti + 1):
                    return True
                groups[gi].pop()
        return False

    # Groups that still need a team from this pot are those currently at size target_size-1
    return recurse(0)


def simulate_one_draw():
    """Return a list of 12 groups (each 4 (team,conf) tuples), or None."""
    groups = [[] for _ in range(12)]

    # Place hosts first
    host_placed = set()
    for host_team, letter in HOST_SLOTS.items():
        gi = GROUP_LETTERS.index(letter)
        conf = teams_df.loc[teams_df["team"] == host_team, "confederation"].iat[0]
        groups[gi].append((host_team, conf))
        host_placed.add(host_team)

    # Remaining Pot 1 teams fill the other 9 groups
    pot1_rest = [(t, c) for p, t, c in TEAMS if p == 1 and t not in host_placed]
    empty_groups = [gi for gi in range(12) if not groups[gi]]
    random.shuffle(pot1_rest)

    def place_pot1_rest(ti, empties):
        if ti == len(pot1_rest):
            return True
        team, conf = pot1_rest[ti]
        candidates = list(empties)
        random.shuffle(candidates)
        for gi in candidates:
            if _confederation_ok(groups, gi, conf):
                groups[gi].append((team, conf))
                new_empties = [g for g in empties if g != gi]
                if place_pot1_rest(ti + 1, new_empties):
                    return True
                groups[gi].pop()
        return False

    if not place_pot1_rest(0, empty_groups):
        return None

    # Pots 2, 3, 4
    for pot_n in (2, 3, 4):
        pot_teams = [(t, c) for p, t, c in TEAMS if p == pot_n]
        if not _place_pot(groups, pot_teams, pot_n):
            return None

    return groups


def run_simulation(n_target=2000, max_attempts=20000):
    """Run until we have n_target valid draws or hit max_attempts."""
    valid = []
    attempts = 0
    while len(valid) < n_target and attempts < max_attempts:
        attempts += 1
        g = simulate_one_draw()
        if g is not None:
            valid.append(g)
    return valid, attempts


print("Running draw simulation...")
draws, total_attempts = run_simulation(n_target=2000)
n_valid = len(draws)
print(f"  {n_valid} valid draws from {total_attempts} attempts")

# Group assignment probabilities (team -> group)
group_prob = {}
for g_idx, groups in enumerate(draws):
    for gi, teams_in_group in enumerate(groups):
        for team, _ in teams_in_group:
            group_prob.setdefault(team, {}).setdefault(GROUP_LETTERS[gi], 0)
            group_prob[team][GROUP_LETTERS[gi]] += 1

rows = []
for team in teams_df["team"]:
    for letter in GROUP_LETTERS:
        count = group_prob.get(team, {}).get(letter, 0)
        rows.append({
            "team": team,
            "group": letter,
            "probability": count / max(n_valid, 1),
        })
draw_prob_df = pd.DataFrame(rows)
draw_prob_df.to_csv(OUT_SIM / "app_draw_probabilities.csv", index=False)

# Matchup frequency (group-stage pairings; every team in a group plays all others)
matchup_count = {}
for groups in draws:
    for teams_in_group in groups:
        names = sorted([t for t, _ in teams_in_group])
        for a, b in itertools.combinations(names, 2):
            matchup_count[(a, b)] = matchup_count.get((a, b), 0) + 1

matchup_rows = []
for (a, b), c in matchup_count.items():
    matchup_rows.append({
        "team_a": a,
        "team_b": b,
        "group_stage_meetings": c,
        "probability": c / max(n_valid, 1),
    })
matchup_df = pd.DataFrame(matchup_rows).sort_values(
    "probability", ascending=False
).reset_index(drop=True)
matchup_df.to_csv(OUT_SIM / "app_matchup_summary.csv", index=False)

# Summary
sim_summary = pd.DataFrame([{
    "n_valid_draws": n_valid,
    "total_attempts": total_attempts,
    "acceptance_rate": round(n_valid / max(total_attempts, 1), 4),
    "pots": 4,
    "groups": 12,
    "teams": 48,
    "host_prefill": "USA -> Group D, Mexico -> Group A, Canada -> Group B",
    "confederation_rule": "Max 2 UEFA per group; max 1 team per other confederation",
    "note": "Demo-scale constrained Monte Carlo. Real FIFA rules are more complex; this is illustrative.",
}])
sim_summary.to_csv(OUT_SIM / "app_simulation_summary.csv", index=False)


# =============================================================================
# 11. KPI table for executive overview
# =============================================================================
total_rev_base = country_summary["total_revenue_base_usd"].sum()
top_venue = venue_summary.iloc[0]
top_country = country_summary.iloc[0]

kpis = pd.DataFrame([
    {"label": "Total projected revenue (base)", "value": f"${total_rev_base/1e9:,.2f}B",
     "raw": total_rev_base, "unit": "usd"},
    {"label": "Top projected venue",            "value": top_venue["venue"],
     "raw": top_venue["total_revenue_base_usd"], "unit": "usd"},
    {"label": "Top projected host country",     "value": top_country["country"],
     "raw": top_country["total_revenue_base_usd"], "unit": "usd"},
    {"label": "Valid simulated draws",          "value": f"{n_valid:,}",
     "raw": n_valid, "unit": "count"},
    {"label": "Main model",                     "value": "revenue_proxy_no_stage_feature",
     "raw": None, "unit": "string"},
])
kpis.to_csv(OUT_APP / "app_kpis.csv", index=False)


# =============================================================================
# 12. Policy scenario baseline table
#     Builds five scenarios by tilting the match-allocation mix.
#     - baseline: current allocation
#     - revenue_first: shift marquee matches toward highest-capacity US venues
#     - fairness: rebalance matches toward under-allocated venues
#     - low_travel: concentrate group-stage matches regionally
#     - balanced: compromise
# =============================================================================

def allocation_to_revenue(venue_alloc: pd.DataFrame) -> pd.DataFrame:
    """Given a venue allocation DataFrame with stage columns, compute proxy revenue."""
    rows = []
    for _, v in venue_alloc.iterrows():
        for _, s in stage_df.iterrows():
            n = int(v[s["alloc_col"]])
            if n <= 0:
                continue
            cap_scale = _cap_factor(v["capacity"])
            per_match = s["median_proxy_revenue_usd"] * cap_scale
            rows.append({
                "venue": v["venue"],
                "country": v["country"],
                "stage": s["stage"],
                "n_matches": n,
                "revenue": per_match * n,
            })
    return pd.DataFrame(rows)


def scenario_revenue_first(base: pd.DataFrame) -> pd.DataFrame:
    """Aggressively concentrate high-value matches in the highest-capacity
    venues. Move knockouts toward 80k+ venues and shift some group matches
    away from smaller hosts."""
    out = base.copy()

    def idx(name):
        return out.index[out["venue"] == name][0]

    # Move 1 QF from smaller knockout hosts to the largest venues
    for donor, recipient in [
        ("Arrowhead Stadium", "AT&T Stadium"),
        ("Mercedes-Benz Stadium", "MetLife Stadium"),
    ]:
        if out.at[idx(donor), "qf_matches"] > 0:
            out.at[idx(donor), "qf_matches"] -= 1
            out.at[idx(recipient), "qf_matches"] += 1

    # Move 1 RO16 from smallest-capacity venues to 80k-club
    for donor, recipient in [
        ("BMO Field", "MetLife Stadium"),
        ("Estadio Akron", "AT&T Stadium"),
        ("Estadio BBVA", "SoFi Stadium"),
    ]:
        if out.at[idx(donor), "ro16_matches"] > 0:
            out.at[idx(donor), "ro16_matches"] -= 1
            out.at[idx(recipient), "ro16_matches"] += 1

    # Group match reshuffle: take 2 from small venues, give to big ones
    for donor, recipient in [
        ("Estadio Akron", "AT&T Stadium"),
        ("BMO Field", "MetLife Stadium"),
    ]:
        if out.at[idx(donor), "group_matches"] > 0:
            out.at[idx(donor), "group_matches"] -= 1
            out.at[idx(recipient), "group_matches"] += 1

    return out


def scenario_fairness(base: pd.DataFrame) -> pd.DataFrame:
    """Protect and elevate smaller host markets. Shift matches from dominant
    US venues to Canadian and Mexican hosts, accepting lower per-match revenue
    in exchange for more even host-country distribution."""
    out = base.copy()

    def idx(name):
        return out.index[out["venue"] == name][0]

    # Move group matches from top 3 US venues toward Canadian/Mexican hosts
    donors = ["MetLife Stadium", "AT&T Stadium", "Mercedes-Benz Stadium"]
    recipients = ["BMO Field", "BC Place", "Estadio Akron",
                  "Estadio BBVA", "Estadio Azteca"]
    for d, r in zip(donors, recipients[:3]):
        if out.at[idx(d), "group_matches"] > 0:
            out.at[idx(d), "group_matches"] -= 1
            out.at[idx(r), "group_matches"] += 1

    # Move a RO16 match from a US venue to Estadio Azteca (historic fairness gesture)
    if out.at[idx("Lincoln Financial Field"), "ro16_matches"] > 0:
        out.at[idx("Lincoln Financial Field"), "ro16_matches"] -= 1
        out.at[idx("Estadio Azteca"), "ro16_matches"] += 1

    # One extra group match to BBVA Monterrey
    out.at[idx("Levi's Stadium"), "group_matches"] = max(
        0, out.at[idx("Levi's Stadium"), "group_matches"] - 1
    )
    out.at[idx("Estadio BBVA"), "group_matches"] += 1

    return out


def scenario_low_travel(base: pd.DataFrame) -> pd.DataFrame:
    """Concentrate group-stage matches in regional clusters to reduce
    intra-tournament travel. Move far-flung venue matches toward hubs in
    each host country."""
    out = base.copy()

    def idx(name):
        return out.index[out["venue"] == name][0]

    # Move group matches out of geographic edges into central hubs
    for donor, recipient in [
        ("Lumen Field", "Levi's Stadium"),       # Seattle -> SF
        ("Hard Rock Stadium", "Mercedes-Benz Stadium"),  # Miami -> Atlanta
        ("Gillette Stadium", "MetLife Stadium"),  # Boston -> NYC
    ]:
        if out.at[idx(donor), "group_matches"] > 0:
            out.at[idx(donor), "group_matches"] -= 1
            out.at[idx(recipient), "group_matches"] += 1

    return out


def scenario_balanced(base: pd.DataFrame) -> pd.DataFrame:
    """A measured compromise: small revenue lift, modest fairness gain."""
    out = base.copy()

    def idx(name):
        return out.index[out["venue"] == name][0]

    # Bump iconic + underused hosts symbolically
    out.at[idx("Estadio Azteca"), "group_matches"] += 1
    out.at[idx("BC Place"), "group_matches"] += 1

    # Take from two smaller-capacity US venues (keeps revenue roughly neutral)
    for d in ["Lincoln Financial Field", "Levi's Stadium"]:
        if out.at[idx(d), "group_matches"] > 0:
            out.at[idx(d), "group_matches"] -= 1

    return out


def compute_policy_metrics(alloc: pd.DataFrame, label: str) -> dict:
    rev = allocation_to_revenue(alloc)
    by_venue = rev.groupby("venue", as_index=False)["revenue"].sum()
    by_country = rev.groupby("country", as_index=False)["revenue"].sum()
    total = rev["revenue"].sum()

    # Host-country equity: 1 - coefficient of variation across countries
    country_rev = by_country["revenue"].values
    cv = country_rev.std() / max(country_rev.mean(), 1)
    equity_score = max(0.0, 1 - cv / 2)  # scaled to roughly [0, 1]

    # Utilization: weighted average of capacity vs stage avg attendance
    util_parts = []
    for _, v in alloc.iterrows():
        total_m = sum(int(v[c]) for c in [
            "group_matches", "ro32_matches", "ro16_matches",
            "qf_matches", "sf_matches", "third_matches", "final_matches"
        ])
        if total_m == 0:
            continue
        cap = v["capacity"]
        # blended stage avg attendance weighted by that venue's mix
        for _, s in stage_df.iterrows():
            n = int(v[s["alloc_col"]])
            if n == 0:
                continue
            fill = min(1.0, s["avg_attendance"] / cap)
            util_parts.append((fill, n))
    util = (
        sum(f * n for f, n in util_parts) / max(sum(n for _, n in util_parts), 1)
    )

    # Travel proxy: higher when group matches are more geographically dispersed.
    # Use the count of distinct regions touched by group matches (regions are
    # simplified as country + US region groups).
    US_REGIONS = {
        "MetLife Stadium": "US-NE", "Gillette Stadium": "US-NE",
        "Lincoln Financial Field": "US-NE",
        "Mercedes-Benz Stadium": "US-SE", "Hard Rock Stadium": "US-SE",
        "AT&T Stadium": "US-SC", "NRG Stadium": "US-SC",
        "Arrowhead Stadium": "US-MW",
        "SoFi Stadium": "US-W", "Levi's Stadium": "US-W", "Lumen Field": "US-W",
    }
    region_counts = {}
    for _, v in alloc.iterrows():
        gm = int(v["group_matches"])
        if gm == 0:
            continue
        region = US_REGIONS.get(v["venue"], v["country"])
        region_counts[region] = region_counts.get(region, 0) + gm
    travel_proxy = len(region_counts)  # number of distinct group-stage regions (lower = less travel)

    return {
        "scenario": label,
        "total_revenue_usd": round(total),
        "revenue_change_vs_baseline_pct": None,  # filled later
        "equity_score": round(equity_score, 3),
        "utilization_proxy": round(util, 3),
        "travel_regions_touched": travel_proxy,
        "top_country": by_country.sort_values("revenue", ascending=False).iloc[0]["country"],
        "top_country_share": round(
            by_country.sort_values("revenue", ascending=False).iloc[0]["revenue"] / total, 3
        ),
    }


base_alloc = venues_df.copy()
scenarios = [
    ("baseline",       base_alloc),
    ("revenue_first",  scenario_revenue_first(base_alloc)),
    ("fairness",       scenario_fairness(base_alloc)),
    ("low_travel",     scenario_low_travel(base_alloc)),
    ("balanced",       scenario_balanced(base_alloc)),
]

scen_metrics = [compute_policy_metrics(a, label) for label, a in scenarios]
baseline_rev = scen_metrics[0]["total_revenue_usd"]
for m in scen_metrics:
    m["revenue_change_vs_baseline_pct"] = round(
        (m["total_revenue_usd"] - baseline_rev) / baseline_rev * 100, 2
    )

scenarios_df = pd.DataFrame(scen_metrics)
scenarios_df.to_csv(OUT_APP / "app_policy_scenarios.csv", index=False)

# Per-venue revenue for each scenario
rows = []
for label, alloc in scenarios:
    rev = allocation_to_revenue(alloc)
    by_venue = rev.groupby(["venue", "country"], as_index=False)["revenue"].sum()
    by_venue["scenario"] = label
    rows.append(by_venue)
scenario_venue_df = pd.concat(rows, ignore_index=True)
scenario_venue_df.to_csv(OUT_APP / "app_policy_venue_revenue.csv", index=False)

# Per-country revenue for each scenario
rows = []
for label, alloc in scenarios:
    rev = allocation_to_revenue(alloc)
    by_country = rev.groupby("country", as_index=False)["revenue"].sum()
    by_country["scenario"] = label
    rows.append(by_country)
scenario_country_df = pd.concat(rows, ignore_index=True)
scenario_country_df.to_csv(OUT_APP / "app_policy_country_revenue.csv", index=False)


# =============================================================================
# 13. Metadata / manifest
# =============================================================================
manifest = {
    "build_version": "2026-04-17-v1",
    "primary_model": "revenue_proxy_no_stage_feature",
    "supporting_model": "revenue_proxy_full (benchmark reference only)",
    "sensitivity_model": "attendance_equivalent_after_price_removal",
    "data_disclaimer": (
        "All revenue figures are scenario / proxy revenue built on assumed "
        "stage-level ticket prices from the executed project summary. They are "
        "not audited observed revenue."
    ),
    "app_ready_files": sorted(p.name for p in OUT_APP.glob("*.csv")),
    "simulation_files": sorted(p.name for p in OUT_SIM.glob("*.csv")),
}
with open(OUT_APP / "manifest.json", "w") as f:
    json.dump(manifest, f, indent=2)

print("\n== Build complete ==")
print(f"app_ready: {sorted(p.name for p in OUT_APP.glob('*.csv'))}")
print(f"simulation: {sorted(p.name for p in OUT_SIM.glob('*.csv'))}")
print(f"Total projected revenue (base): ${total_rev_base/1e9:,.2f}B")
print(f"Top venue: {top_venue['venue']} at ${top_venue['total_revenue_base_usd']/1e6:,.1f}M")
print(f"Valid draws: {n_valid}")
